routes/web.php
<?php


Auth::routes();

//Simpan Route nya dibawah yang sudah dikasih komentar biar rapih hehe
//Route pertama aplikasi dijalankan

Route::get('/', 'ContentController@welcome');

Route::get('/error', function () {
    return view('error');
});




// DAFTAR ROLE
// id 1 = Admin
//    2 = Siswa
//    3 = Guru

//Semua user bisa mengakses halaman home/dashboard
Route::group(['middleware' => ['auth']], function(){
    //Route Home
     Route::get('/home', 'HomeController@index')->name('home');

});

//Hanya bisa diakses Oleh Admin
Route::group(['middleware' => ['auth', 'role: 1']], function(){

    //Route User
    Route::resource('users', UserController::class);

    //Route Mapel
    Route::resource('mapels', MapelController::class);

    //Route Jadwal
    Route::resource('jadwals', JadwalController::class);

    //Route Kelas
    Route::resource('kelas', KelasController::class);

    //Route Siswa
    Route::resource('siswas', SiswaController::class);

    //Route Guru
    Route::resource('gurus', GuruController::class);

    //Route Untuk merubah content
    Route::resource('content', ContentController::class);
});

//Hanya bisa diakses oleh Admin dan Siswa
Route::group(['middleware' => ['auth', 'role: 1, 2']], function(){

    //Profile Siswa
    Route::resource('profileSiswa', ProfileSiswaController::class);

    //Cetak PDF Tabel Siswas\
    Route::get('/cetak_siswa','CetakPdfController@cetakSiswa');

    //Ubah Password

});


//Hanya bisa diakses oleh Admin dan Guru
Route::group(['middleware' => ['auth','role: 1,3']], function(){
    //Profile Guru
    Route::resource('profileGuru', ProfileGuruController::class);

    //Cetak PDF Tabel Guru
    Route::get('/cetak_guru','CetakPdfController@cetakGuru');
});

app/Guru.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guru extends Model
{
    // protected $table = "siswas";
    protected $guarded = ['id'];

    public function mapel()
    {
        return $this->belongsTo(Mapel::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function jadwal(){
        return $this->hasMany(Jadwal::class);
    }
}

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use App\Guru;
use App\User;
use App\Mapel;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use RealRashid\SweetAlert\Facades\Alert;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        $mapel = Mapel::all();
        $guru = Guru::latest()->paginate(5);
        // dd($guru->all());
        return view('page.guru.index', compact('guru','user','mapel'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mapel = mapel::all();
        $user = User::all();
        $guru = guru::all();
        $roles = Role::all();
        return view('page.guru.create', compact('guru','mapel','user', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nip' => 'required|unique:gurus',
            'alamat' => 'required',
            'no_hp' => 'required|min:11|max:13',
            'mapel_id' => 'required',
            'name' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:8|string|confirmed',
            'role_id' => 'required',
        ],
        [
           'nip.required' => 'NIP tidak boleh kosong',
           'nip.unique' => 'NIP sudah digunakan',
           'alamat.required' => 'Alamat tidak boleh kosong',
           'no_hp.required' => 'Nomor HP tidak boleh kosong',
           'no_hp.min' => 'Minimal 11 karakter',
           'no_hp.max' => 'Maximal 13 karakter',
           'mapel_id.required' => 'Mapel tidak boleh kosong',
           'name.required' => 'Nama tidak boleh kosong',
           'email.required' => 'Email tidak boleh kosong',
           'email.unique' => 'Email sudah digunakan',
           'password.required' => 'Password tidak boleh kosong',
           'password.min' => 'Minimal 8 karakter',
           'password.confirmed' => 'Password tidak sesuai',
           'role_id.required' => 'Role tidak boleh kosong',
        ]);

        $user = User::create([
            "name" => $request["name"],
            "email" => $request["email"],
            "password" => Hash::make($request['password']),
            "role_id" => $request["role_id"]
        ]);
        Guru::create([
            "nip" => $request["nip"],
            "alamat" => $request["alamat"],
            "no_hp" => $request["no_hp"],
            "user_id" => $user->id,
            "mapel_id" => $request["mapel_id"]
        ]);
        Alert::success('Berhasil', 'Berhasil Menambahkan Data Guru Baru');
        return redirect('gurus');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $guru = guru::where('id', $id)->first();
        return view('page.guru.show', compact('guru'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::all();
        $mapel = mapel::all();
        $guru = guru::where('id', $id)->first();
        return view('page.guru.edit', compact( 'user','mapel','guru'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'name' => 'required',
            'alamat' => 'required',
            'no_hp' => 'required|min:11|max:13',
            'mapel_id' => 'required',
        ],
        [
           'name.required' => 'Nama Lengkap tidak boleh kosong',

           'alamat.required' => 'Alamat tidak boleh kosong',
           'no_hp.required' => 'Nomor HP tidak boleh kosong',
           'no_hp.min' => 'Minimal 11 karakter',
           'no_hp.max' => 'Maximal 13 karakter',
           'mapel_id.required' => 'Mapel tidak boleh kosong',
        ]);
        $guru = guru::where('id', $id)->update([
            "alamat" => $request["alamat"],
            "no_hp" => $request["no_hp"],
            "mapel_id" => $request["mapel_id"],
        ]);

        // $findUser = siswa::where("user_id", 7)->first();

        $user = User::where('id', $request['user_id'])->update([
            "name" => $request["name"]
        ]);

        Alert::success('Berhasil', 'Berhasil Update Data Guru Baru');
        return redirect('gurus');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $query = guru::where('id', $id)->delete();
        return redirect('gurus');
    }
}

resources/views/page/guru/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Guru')

@section('section-content')

<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Tambah data Guru</h3>
            <p>Untuk menambahkan data Guru baru silahkan isi data berikut</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Guru</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('gurus.store') }}" method="post">
                        @csrf
                        <div class="card-body">
                           <div class="form-group">
                                <label for="nip">NIP</label>
                                <input type="text" name="nip" class="form-control @error('nip') is-invalid @enderror" id="nip" value="{{ old('nip') }}">
                                @error('nip')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="nama">Nama Lengkap</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" value="{{ old('name') }}">
                                @error('name')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat Rumah</label>
                                <input type="text" name="alamat" class="form-control @error('alamat') is-invalid @enderror" value="{{ old('alamat') }}">
                                @error('alamat')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="no_hp">Nomer HP/WA</label>
                                <input type="number" name="no_hp" class="form-control @error('no_hp') is-invalid @enderror" value="{{ old('no_hp') }}">
                                @error('no_hp')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="mapel_id">Mata Pelajaran</label>
                                <select class="form-control form-control-sm @error('mapel_id') is-invalid @enderror" name="mapel_id">
                                    <option value="0" selected disabled>Pilih Mapel</option>
                                    @foreach ( $mapel as $data )
                                        @if (old('mapel_id') == $data->id)
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('mapel_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}">
                                @error('email')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="role_id">Role</label>
                                <select class="form-control form-control-sm @error('role_id') is-invalid @enderror" name="role_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $roles as $data )
                                        @if (old('role_id') == $data->id)
                                            <option value="{{ $data->id }}">{{ $data->name }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('role_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="********" autocomplete="new-password">
                                @error('password')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="password-confirm">Confirm Password</label>
                                <input id="password-confirm" type="password" name="password_confirmation" class="form-control" placeholder="********" autocomplete="new-password">
                            </div>

                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/page/guru/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Data Guru')

@section('section-content')
<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Edit data Guru</h3>
            <p>Untuk edit data Guru silahkan isi data berikut</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Guru</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('gurus.update', $guru->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group">
                                <label for="nip">NIP</label>
                                <input type="text" name="nip" class="form-control @error('nip') is-invalid @enderror" id="nis" value="{{ old('nip', $guru->nip) }}" disabled>
                                @error('nip')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="name">Nama</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" value="{{ old('name', $guru->user->name) }}">
                                @error('name')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat Rumah</label>
                                <input type="text" name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="alamat" value="{{ old('alamat', $guru->alamat) }}">
                                @error('alamat')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="no_hp">Nomor HP</label>
                                <input type="text" name="no_hp" class="form-control @error('no_hp') is-invalid @enderror" id="no_hp" value="{{ old('no_hp', $guru->no_hp) }}">
                                @error('no_hp')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group" disabled hidden>
                                <label for="user_id">User ID</label>
                                <input type="text" name="user_id" class="form-control @error('user_id') is-invalid @enderror" id="user_id" value="{{ old('user_id', $guru->user_id) }}">
                                @error('user_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="mapel_id">Mapel</label>
                                <select class="form-control form-control-sm @error('mapel_id') is-invalid @enderror" name="mapel_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $mapel as $data )
                                        @if (old('mapel_id', $guru->mapel_id) == $data->id)
                                            <option value="{{ $data->id }}" selected>{{ $data->nama }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('mapel_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/page/guru/index.blade.php
@extends('layouts.app')

@section('title', 'Halaman Guru')

@section('section-content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Guru</h1>
        <p class="mb-4">Berikut merupakan data guru</p>
        <a href="{{ route('gurus.create') }}" class="btn btn-primary mb-2">Tambah Guru</a>
        <a href="/cetak_guru" class="btn btn-danger mb-2" target="a_blank">Cetak Daftar Guru</a>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Table Guru</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 5%">No</th>
                                <th class="text-center" style="">NIP</th>
                                <th class="text-center" style="">Nama</th>
                                <th class="text-center" style="width: 10%">Mata Pelajaran</th>
                                <th class="text-center" style="width: 25%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($guru as $key => $data )
                                <tr>
                                    <td class="text-center">{{$guru->firstItem() + $key}}</td>
                                    <td>{{ $data->nip }}</td>
                                    <td>{{ $data->user->name }}</td>
                                    <td>{{ $data->mapel->nama }}</td>
                                    <td class="text-center">
                                        <form action="{{ route('gurus.destroy', $data->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('gurus.show', $data->id) }}" class="btn btn-info btn-sm">Detail</a>
                                            <a href="{{ route('gurus.edit', $data->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                            <input type="submit" class="btn btn-danger my-1 btn-sm" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8" class="text-center text-danger">Data Kosong !</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>

                    <div class="pull-left">
                        Showing
                        {{ $guru->firstItem() }}
                        To
                        {{ $guru->lastItem() }}
                        of
                        {{ $guru->total() }}
                        {{-- TOTAL tidak bisa digunakan ketika pake simplePaginate--}}
                        entries
                    </div>
                    <div class="col float-right">
                        <div class="pagination-block float-right">
                            {{-- hapus class pagination-block, jika menggunakan simplePaginate --}}
                            {{-- hapus isi didalam kurung links, jika menggunakan simplePaginate --}}

                            {{ $guru->links('layouts.paginate.paginationlinks') }}
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/page/guru/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Data Guru')

@section('section-content')
    <h1 class="h3 mb-2 text-gray-800">Detail Guru</h1>
    <div class="card">
       <div class="card-body">
            <p>NIP : {{ $guru->nip }}</p>
            <p>Nama : {{ $guru->user->name }}</p>
            <p>Alamat : {{ $guru->alamat }}</p>
            <p>Nomor HP : {{ $guru->no_hp }}</p>
            <p>Mata Pelajaran : {{ $guru->mapel->nama }}</p>

            <a class="btn btn-primary" href="{{ route('gurus.index') }}">Kembali</a>
       </div>
    </div>
@endsection