routes/web.php
<?php


Auth::routes();

//Simpan Route nya dibawah yang sudah dikasih komentar biar rapih hehe
//Route pertama aplikasi dijalankan

Route::get('/', 'ContentController@welcome');

Route::get('/error', function () {
    return view('error');
});




// DAFTAR ROLE
// id 1 = Admin
//    2 = Siswa
//    3 = Guru

//Semua user bisa mengakses halaman home/dashboard
Route::group(['middleware' => ['auth']], function(){
    //Route Home
     Route::get('/home', 'HomeController@index')->name('home');

});

//Hanya bisa diakses Oleh Admin
Route::group(['middleware' => ['auth', 'role: 1']], function(){

    //Route User
    Route::resource('users', UserController::class);

    //Route Mapel
    Route::resource('mapels', MapelController::class);

    //Route Jadwal
    Route::resource('jadwals', JadwalController::class);

    //Route Kelas
    Route::resource('kelas', KelasController::class);

    //Route Siswa
    Route::resource('siswas', SiswaController::class);

    //Route Guru
    Route::resource('gurus', GuruController::class);

    //Route Untuk merubah content
    Route::resource('content', ContentController::class);
});

//Hanya bisa diakses oleh Admin dan Siswa
Route::group(['middleware' => ['auth', 'role: 1, 2']], function(){

    //Profile Siswa
    Route::resource('profileSiswa', ProfileSiswaController::class);

    //Cetak PDF Tabel Siswas\
    Route::get('/cetak_siswa','CetakPdfController@cetakSiswa');

    //Ubah Password

});


//Hanya bisa diakses oleh Admin dan Guru
Route::group(['middleware' => ['auth','role: 1,3']], function(){
    //Profile Guru
    Route::resource('profileGuru', ProfileGuruController::class);

    //Cetak PDF Tabel Guru
    Route::get('/cetak_guru','CetakPdfController@cetakGuru');
});

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jadwal extends Model
{
    //
    protected $guarded = ['id'];

    public function guru()
    {
        return $this->belongsTo(Guru::class);
    }
    public function kelas()
    {
        return $this->belongsTo(kelas::class);
    }
}

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use App\Jadwal;
use App\Guru;
use App\User;
use App\Mapel;
use App\Kelas;
use App\Role;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class JadwalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        $mapel = Mapel::all();
        $kelas = kelas::all();
        $guru = Guru::all();
        $jadwal = Jadwal::latest()->paginate(5);
        // dd($guru->all());
        return view('page.jadwal.index', compact('jadwal','user','mapel','guru','kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelas = kelas::all();
        $guru = Guru::all();
        $jadwal = Jadwal::all();
        return view('page.jadwal.create', compact('guru','kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'hari' => 'required',
            'sesi' => 'required',
            'kelas_id' => 'required',
            'guru_id' => 'required',
        ],
        [
           'hari.required' => 'Hari tidak boleh kosong',
           'sesi.required' => 'Sesi tidak boleh kosong',
           'kelas_id.required' => 'Kelas tidak boleh kosong',
           'guru_id.required' => 'Guru tidak boleh kosong',
        ]);
        Jadwal::create([
            "hari" => $request["hari"],
            "sesi" => $request["sesi"],
            "kelas_id" => $request["kelas_id"],
            "guru_id" => $request["guru_id"]
        ]);
        Alert::success('Berhasil', 'Berhasil Menambahkan Data Jadwal Baru');
        return redirect('jadwals');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Jadwal  $jadwal
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jadwal = Jadwal::where('id', $id)->first();
        return view('page.jadwal.show', compact('jadwal'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Jadwal  $jadwal
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kelas = kelas::all();
        $guru = Guru::all();
        $jadwal = Jadwal::where('id', $id)->first();
        return view('page.jadwal.edit', compact( 'kelas','guru','jadwal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Jadwal  $jadwal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'hari' => 'required',
            'sesi' => 'required',
            'kelas_id' => 'required',
            'guru_id' => 'required',
        ],
        [
           'hari.required' => 'Hari tidak boleh kosong',
           'sesi.required' => 'Sesi tidak boleh kosong',
           'kelas_id.required' => 'Kelas tidak boleh kosong',
           'guru_id.required' => 'Guru tidak boleh kosong',
        ]);
        $jadwal = Jadwal::where('id', $id)->update([
            "hari" => $request["hari"],
            "sesi" => $request["sesi"],
            "kelas_id" => $request["kelas_id"],
            "guru_id" => $request["guru_id"]
        ]);
        Alert::success('Berhasil', 'Berhasil Update Data Jadwal');
        return redirect('jadwals');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Jadwal  $jadwal
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $query = jadwal::where('id', $id)->delete();
        return redirect('jadwals');
    }
}

resources/views/page/jadwal/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Jadwal')

@section('section-content')

<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Tambah data Jadwal</h3>
            <p>Untuk menambahkan data Jadwal baru silahkan isi data berikut</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Jadwal</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('jadwals.store') }}" method="post">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="hari">Hari</label>
                                <select class="form-control form-control-sm @error('hari') is-invalid @enderror" name="hari">
                                    <option value="0" selected disabled>Pilih Data Hari</option>
                                    <option value="Senin">Senin</option>
                                    <option value="Selasa">Selasa</option>
                                    <option value="Rabu">Rabu</option>
                                    <option value="Kamis">Kamis</option>
                                    <option value="Jumat">Jumat</option>
                                </select>
                                @error('hari')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="sesi">Sesi</label>
                                <select class="form-control form-control-sm @error('sesi') is-invalid @enderror" name="sesi">
                                    <option value="0" selected disabled>Pilih Data Sesi</option>
                                    <option value="Pagi">Pagi</option>
                                    <option value="Siang">Siang</option>
                                </select>
                                @error('sesi')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="kelas_id">Kelas</label>
                                <select class="form-control form-control-sm @error('kelas_id') is-invalid @enderror" name="kelas_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $kelas as $data )
                                        @if (old('kelas_id') == $data->id)
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('kelas_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="guru_id">Guru</label>
                                <select class="form-control form-control-sm @error('guru_id') is-invalid @enderror" name="guru_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $guru as $data )
                                        @if (old('guru_id') == $data->id)
                                            <option value="{{ $data->id }}">{{ $data->user->name }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->user->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('guru_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/page/jadwal/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Data Jadwal')

@section('section-content')
<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Edit data Jadwal</h3>
            <p>Untuk edit data Jadwal silahkan isi data berikut</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Jadwal</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('jadwals.update', $jadwal->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            
                            <div class="form-group">
                                <label for="hari">Hari</label>
                                <select class="form-control form-control-sm @error('hari') is-invalid @enderror" name="hari">
                                    <option value="{{ old('hari', $jadwal->hari) }}" selected>{{ old('hari', $jadwal->hari) }}</option>
                                    <option value="Senin">Senin</option>
                                    <option value="Selasa">Selasa</option>
                                    <option value="Rabu">Rabu</option>
                                    <option value="Kamis">Kamis</option>
                                    <option value="Jumat">Jumat</option>
                                </select>
                                @error('hari')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="sesi">Sesi</label>
                                <select class="form-control form-control-sm @error('sesi') is-invalid @enderror" name="sesi">
                                    <option value="{{ old('sesi', $jadwal->sesi) }}" selected>{{ old('sesi', $jadwal->sesi) }}</option>
                                    <option value="Pagi">Pagi</option>
                                    <option value="Siang">Siang</option>
                                </select>
                                @error('sesi')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="kelas_id">Kelas</label>
                                <select class="form-control form-control-sm @error('kelas_id') is-invalid @enderror" name="kelas_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $kelas as $data )
                                        @if (old('kelas_id', $jadwal->kelas_id) == $data->id)
                                            <option value="{{ $data->id }}" selected>{{ $data->nama }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('kelas_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="guru_id">Guru</label>
                                <select class="form-control form-control-sm @error('guru_id') is-invalid @enderror" name="guru_id">
                                    <option value="0" selected disabled>Pilih Data</option>
                                    @foreach ( $guru as $data )
                                        @if (old('guru_id', $jadwal->guru_id) == $data->id)
                                            <option value="{{ $data->id }}" selected>{{ $data->user->name }}</option>
                                        @else
                                            <option value="{{ $data->id }}">{{ $data->user->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('guru_id')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/page/jadwal/index.blade.php
@extends('layouts.app')

@section('title', 'Halaman Jadwal')

@section('section-content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Jadwal</h1>
        <p class="mb-4">Berikut merupakan data Jadwal</p>
        <a href="{{ route('jadwals.create') }}" class="btn btn-primary mb-2">Tambah Jadwal</a>
        <!--<a href="/cetak_guru" class="btn btn-danger mb-2" target="a_blank">Cetak Daftar Guru</a>
         DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Table Jadwal</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 5%">No</th>
                                <th class="text-center" style="">Hari</th>
                                <th class="text-center" style="">Sesi</th>
                                <th class="text-center" style="">Kelas</th>
                                <th class="text-center" style="width: 10%">Guru</th>
                                <th class="text-center" style="width: 25%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($jadwal as $key => $data )
                                <tr>
                                    <td class="text-center">{{$jadwal->firstitem() + $key}}</td>
                                    <td>{{ $data->hari }}</td>
                                    <td>{{ $data->sesi }}</td>
                                    <td>{{ $data->kelas->nama }}</td>
                                    <td>{{ $data->guru->user->name }}</td>
                                    <td class="text-center">
                                        <form action="{{ route('jadwals.destroy', $data->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('jadwals.show', $data->id) }}" class="btn btn-info btn-sm">Detail</a>
                                            <a href="{{ route('jadwals.edit', $data->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                            <input type="submit" class="btn btn-danger my-1 btn-sm" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8" class="text-center text-danger">Data Kosong !</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>

                    <div class="pull-left">
                        Showing
                        {{ $jadwal->firstItem() }}
                        To
                        {{ $jadwal->lastItem() }}
                        of
                        {{ $jadwal->total() }}
                        {{-- TOTAL tidak bisa digunakan ketika pake simplePaginate--}}
                        entries
                    </div>
                    <div class="col float-right">
                        <div class="pagination-block float-right">
                            {{-- hapus class pagination-block, jika menggunakan simplePaginate --}}
                            {{-- hapus isi didalam kurung links, jika menggunakan simplePaginate --}}

                            {{ $jadwal->links('layouts.paginate.paginationlinks') }}
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/page/jadwal/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Data Guru')

@section('section-content')
    <h1 class="h3 mb-2 text-gray-800">Detail Guru</h1>
    <div class="card">
       <div class="card-body">
            <p>Hari : {{ $jadwal->hari }}</p>
            <p>Sesi : {{ $jadwal->sesi}}</p>
            <p>Kelas : {{ $jadwal->kelas->nama }}</p>
            <p>Guru : {{ $jadwal->guru->user->name }}</p>
            <p>Mata Pelajaran : {{ $jadwal->guru->mapel->nama }}</p>

            <a class="btn btn-primary" href="{{ route('jadwals.index') }}">Kembali</a>
       </div>
    </div>
@endsection