routes/web.php
<?php


Auth::routes();

//Simpan Route nya dibawah yang sudah dikasih komentar biar rapih hehe
//Route pertama aplikasi dijalankan

Route::get('/', 'ContentController@welcome');

Route::get('/error', function () {
    return view('error');
});




// DAFTAR ROLE
// id 1 = Admin
//    2 = Siswa
//    3 = Guru

//Semua user bisa mengakses halaman home/dashboard
Route::group(['middleware' => ['auth']], function(){
    //Route Home
     Route::get('/home', 'HomeController@index')->name('home');

});

//Hanya bisa diakses Oleh Admin
Route::group(['middleware' => ['auth', 'role: 1']], function(){

    //Route User
    Route::resource('users', UserController::class);

    //Route Mapel
    Route::resource('mapels', MapelController::class);

    //Route Jadwal
    Route::resource('jadwals', JadwalController::class);

    //Route Kelas
    Route::resource('kelas', KelasController::class);

    //Route Siswa
    Route::resource('siswas', SiswaController::class);

    //Route Guru
    Route::resource('gurus', GuruController::class);

    //Route Untuk merubah content
    Route::resource('content', ContentController::class);
});

//Hanya bisa diakses oleh Admin dan Siswa
Route::group(['middleware' => ['auth', 'role: 1, 2']], function(){

    //Profile Siswa
    Route::resource('profileSiswa', ProfileSiswaController::class);

    //Cetak PDF Tabel Siswas\
    Route::get('/cetak_siswa','CetakPdfController@cetakSiswa');

    //Ubah Password

});


//Hanya bisa diakses oleh Admin dan Guru
Route::group(['middleware' => ['auth','role: 1,3']], function(){
    //Profile Guru
    Route::resource('profileGuru', ProfileGuruController::class);

    //Cetak PDF Tabel Guru
    Route::get('/cetak_guru','CetakPdfController@cetakGuru');
});

app/Mapel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mapel extends Model
{
    //
    // protected $fillable = ['nama'];
    protected $guarded = ['id'];

     public function guru(){
        return $this->hasMany(Guru::class);
    }
}

app/Http/Controllers/MapelController.php
<?php

namespace App\Http\Controllers;

use App\Mapel;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class MapelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mapel = mapel::latest()->paginate(5);
        return view('page.mapel.index', compact('mapel'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mapel = mapel::all();
        return view('page.mapel.create', compact('mapel'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['nama' => 'required',],['nama.required' => 'Nama tidak boleh kosong',]);
        $query = mapel::create(["nama" => $request["nama"],]);

        Alert::success('Berhasil', 'Berhasil Menambahkan Data Mata Pelajaran Baru');
        return redirect('mapels');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Mapel  $mapel
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mapel = mapel::where('id', $id)->first();
        return view('page.mapel.show', compact('mapel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Mapel  $mapel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mapel = mapel::where('id', $id)->first();
        return view('page.mapel.edit', compact('mapel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Mapel  $mapel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(['nama' => 'required',],['nama.required' => 'Nama tidak boleh kosong',]);
        $query = mapel::where('id', $id)->update(["nama" => $request["nama"]]);
        
        Alert::success('Berhasil', 'Berhasil Update Data Mata Pelajaran');
        return redirect('mapels');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Mapel  $mapel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = mapel::where('id', $id)->delete();
        return redirect('mapels');
    }
}

resources/views/page/mapel/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Mapel')

@section('section-content')

<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Tambah data Mata Pelajaran</h3>
            <p>Untuk menambahkan data mata pelajaran baru silahkan isi data berikut</p>
        </div> 
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Mapel</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('mapels.store') }}" method="post">
                        @csrf
                        <div class="card-body">
                           
                            <div class="form-group">
                                <label for="nama">Nama</label>
                                <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama">
                                @error('nama')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/page/mapel/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Data Mapel')

@section('section-content')
<div class="row">
    <div class="col-md-12 d-flex justify-content-between">
        <div class="col-md-4">
            <h3>Edit data Mata Pelajaran</h3>
            <p>Untuk edit data Mapel silahkan isi data berikut</p>
        </div>
        <div class="col-md-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Mapel</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('mapels.update', $mapel->id) }}" method="post">
                        @csrf
                        @method('PUT')
                      
                            <div class="form-group">
                                <label for="nama">Nama</label>
                                <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama" value="{{ old('nama', $mapel->nama) }}">
                                @error('nama')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/page/mapel/index.blade.php
@extends('layouts.app')

@section('title', 'Halaman Mata Pelajaran')

@section('section-content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Mata Pelajaran</h1>
        <p class="mb-4">Berikut merupakan data mata pelajaran</p>
        <a href="{{ route('mapels.create') }}" class="btn btn-primary mb-2">Tambah Mapel</a>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Table Mata Pelajaran</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 5%">No</th>
                                <th class="text-center" style="">Nama</th>
                                <th class="text-center" style="width: 25%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($mapel as $key => $data )
                                <tr>
                                    <td class="text-center">{{$key+1}}</td>
                                    <td>{{ $data->nama }}</td>
                                    <td class="text-center">
                                        <form action="{{ route('mapels.destroy', $data->id) }}" method="POST" onsubmit="return confirm('Yakin Hapus Data?')">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('mapels.show', $data->id) }}" class="btn btn-info btn-sm">Detail</a>
                                            <a href="{{ route('mapels.edit', $data->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                            <input type="submit" class="btn btn-danger my-1 btn-sm" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8" class="text-center text-danger">Data Kosong !</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/page/mapel/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Data Mapel')

@section('section-content')
    <h1 class="h3 mb-2 text-gray-800">Detail Mata Pelajaran</h1>
    <div class="card">
       <div class="card-body">
            <p>ID Mapel : {{ $mapel->id }}</p>
            <p>Nama : {{ $mapel->nama }}</p>
            <a class="btn btn-primary" href="{{ route('mapels.index') }}">Kembali</a>
       </div>
    </div>
@endsection