routes/web.php
<?php


Auth::routes();

//Simpan Route nya dibawah yang sudah dikasih komentar biar rapih hehe
//Route pertama aplikasi dijalankan

Route::get('/', 'ContentController@welcome');

Route::get('/error', function () {
    return view('error');
});




// DAFTAR ROLE
// id 1 = Admin
//    2 = Siswa
//    3 = Guru

//Semua user bisa mengakses halaman home/dashboard
Route::group(['middleware' => ['auth']], function(){
    //Route Home
     Route::get('/home', 'HomeController@index')->name('home');

});

//Hanya bisa diakses Oleh Admin
Route::group(['middleware' => ['auth', 'role: 1']], function(){

    //Route User
    Route::resource('users', UserController::class);

    //Route Mapel
    Route::resource('mapels', MapelController::class);

    //Route Jadwal
    Route::resource('jadwals', JadwalController::class);

    //Route Kelas
    Route::resource('kelas', KelasController::class);

    //Route Siswa
    Route::resource('siswas', SiswaController::class);

    //Route Guru
    Route::resource('gurus', GuruController::class);

    //Route Untuk merubah content
    Route::resource('content', ContentController::class);
});

//Hanya bisa diakses oleh Admin dan Siswa
Route::group(['middleware' => ['auth', 'role: 1, 2']], function(){

    //Profile Siswa
    Route::resource('profileSiswa', ProfileSiswaController::class);

    //Cetak PDF Tabel Siswas\
    Route::get('/cetak_siswa','CetakPdfController@cetakSiswa');

    //Ubah Password

});


//Hanya bisa diakses oleh Admin dan Guru
Route::group(['middleware' => ['auth','role: 1,3']], function(){
    //Profile Guru
    Route::resource('profileGuru', ProfileGuruController::class);

    //Cetak PDF Tabel Guru
    Route::get('/cetak_guru','CetakPdfController@cetakGuru');
});

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->email }}</span>
                <img class="img-profile rounded-circle"
                    src="{{ asset('assets/img/undraw_profile.svg') }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                @if (auth()->user()->role_id == '2');
                    <a class="dropdown-item" href="{{ route('profileSiswa.index') }}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile Siswa
                    </a>
                    <div class="dropdown-divider"></div>
                @endif
                @if (auth()->user()->role_id == '3');
                    <a class="dropdown-item" href="{{ route('profileGuru.index') }}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile Guru
                    </a>
                    <div class="dropdown-divider"></div>
                @endif

                <a class="dropdown-item" href="{{ route('logout') }}" data-toggle="modal" data-target="#logoutModal" >
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    {{ __('Logout') }}
                </a>
            </div>
        </li>
    </ul>

</nav>

resources/views/layouts/partials/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Sistem Informasi</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ Request::is('home') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    @if (auth()->user()->role_id == '1');
        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            DATA
        </div>

         <!-- Nav Item - Tables -->
        <li class="nav-item {{ Request::is('gurus*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('gurus.index') }}">
                <i class="fas fa-user-md"></i>
                <span>Guru</span></a>
        </li>

        <li class="nav-item {{ Request::is('siswas*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('siswas.index') }}">
                <i class="fas fa-solid fa-graduation-cap"></i>
                <span>Siswa</span></a>
        </li>

        <li class="nav-item {{ Request::is('jadwal*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('jadwals.index') }}">
                <i class="fas fa-fw fa-table"></i>
                <span>Jadwal</span></a>
        </li>

        <li class="nav-item {{ Request::is('kelas*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('kelas.index') }}">
                <i class="fas fa-fw fa-table"></i>
                <span>Kelas</span></a>
        </li>
        <li class="nav-item {{ Request::is('mapels*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('mapels.index') }}">
                <i class="fas fa-fw fa-table"></i>
                <span>Mapel</span></a>
        </li>

    @endif

    <!-- Divider -->
    <hr class="sidebar-divider">

    @if (auth()->user()->role_id == '1');
         <!-- Heading -->
        <div class="sidebar-heading">
            Settings
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item {{ Route::is('users*') || Route::is('content*') ? 'active' : '' }}">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Management Users</span>
            </a>
            <div id="collapseTwo" class="collapse {{ Route::is('users*')|| Route::is('content*') ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Management User</h6>
                    <a class="collapse-item {{ Route::is('users*') ? 'active' : '' }}" href="{{ route('users.index') }}">User</a>
                    <a class="collapse-item {{ Route::is('content*') ? 'active' : '' }}" href="{{ route('content.index') }}">Rubah Content</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

    @endif


    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>